development:
  adapter: postgresql
  encoding: unicode
  database: my_rp_development
  pool: 5
  username: my_rp
  password: '12345'

test:
  adapter: postgresql
  encoding: unicode
  database: my_rp_test
  pool: 5
  username: my_rp
  password: '12345'

production:
  adapter: postgresql
  encoding: unicode
  database: my_rp_production
  pool: 5
  username: my_rp
  password: '12345'
